### ISSUE TITLE
Navigation UI

### ISSUE THREAD

**Issue by frankmaayn** [frankmaayn/app-A#26]
- This has been implemented in the code will be merged to the 'dev' branch
- Gaven has added a basic ui for the maps, we just need to modify and add coordinates
- If the 'Map Activity' is not running correctly, uninstall then install the app in the emulator

- [x] Implement tapping on locations from directory screen to open up navigation from user's location to the selected location
- [x] Thursday: Tapping from directory should open up the navigation directly
- [x] Install mapbox navigation ui sdk dependencies
- [x] Build a basic map activity
solution: https://stackoverflow.com/questions/56266801/java-net-socketexception-socket-failed-eperm-operation-not-permitted
- [x] Connect navigation button to map activity
- [x] Display current location

**Comment by dpalencia** [comment]
- [ ] Set up route events/maneuver instructions
- [ ] Display route instructions
- [ ] Display list of all instructions with eta summary
- [ ] Convert direction activity to Kotlin

**Comment by indomie858** [comment]
## Link to Mapbox core examples github repo
https://github.com/mapbox/mapbox-navigation-android/tree/master/examples/src/main/java/com/mapbox/navigation/examples/core

**Comment by frankmaayn** [comment]
Issue is closed
