### ISSUE TITLE
Map Activity - Points

### ISSUE THREAD

**Issue by dpalencia** [frankmaayn/app-A#39]
- [ ] Populate map activity with points from latitudes and longitudes
- [ ] Tap a location to set a route
- [ ] Button to start navigation

**Comment by indomie858** [comment]
https://docs.mapbox.com/help/tutorials/create-a-custom-style/#add-a-component

**Comment by frankmaayn** [comment]
addMarker, markerOPtions, etc. has been deprecated
use this instead:
https://docs.mapbox.com/android/plugins/overview/annotation/

**Comment by frankmaayn** [comment]
Using the style URL
https://docs.mapbox.com/android/maps/examples/use-a-mapbox-studio-style/

**Comment by indomie858** [comment]
GeoJSON docs
https://docs.mapbox.com/android/java/overview/geojson/

**Comment by indomie858** [comment]
Data driven styling guide
https://docs.mapbox.com/android/maps/overview/data-driven-styling/

**Comment by Ryunosuke500** [comment]
I updated MapActivity. It meets the requirement.
