### ISSUE TITLE
Settings UI

### ISSUE THREAD

**Issue by indomie858** [frankmaayn/app-A#49]
- [x] Replace options for SettingsFragment
- [ ] Get at least one option working (possibly text size?)

Files used for SettingsFragment:
- SettingsFragment.kt
- root_preferences.xml

Currently the options that are displayed on settings screen is not relevant to our project. Replace these options with ones such as text size, theme, etc.

Branch from dev to work on this

![Screenshot 2020-10-21 122458](https://user-images.githubusercontent.com/55901980/96772899-a3438500-1398-11eb-9403-3a04dbd1e95b.png)

**Comment by dpalencia** [comment]
What other settings do we want?

**Comment by frankmaayn** [comment]
We now have a settings fragment with an option to change theme
