### ISSUE TITLE
Settings Overlaid on top of Home when navigating to settings

### ISSUE THREAD

**Issue by dpalencia** [frankmaayn/app-A#54]
Sometimes, when you tap the settings button, you see both fragments overlaid on top of each other. Also, the Tutorial screen content seems to go blank when this happens.

**Comment by indomie858** [comment]
#### Steps to recreate bug in app
1. Click on theme in settings tab
2. Set theme to dark theme
3. Close and restart the app

App works normally when light theme is selected before restarting the app

**Comment by indomie858** [comment]
@Ryunosuke500 can you try to find out what is causing this? It has something to do with the dark theme setting

**Comment by Ryunosuke500** [comment]
Yeah, I am trying to fix the bug.

**Comment by Ryunosuke500** [comment]
Overlaid is fixed.
I changed fragment transaction method in MainActivity.

Tutorial text problem is under investigation...
